[<RequireQualifiedAccess>]
module Fasta = 
    type internal Content = { C_or_G:double; Other:double; }

    type Fasta = 
        { Name:string; DNA:string; GC_Content:double; }
        static member print (fasta:Fasta) = printfn "%s" (sprintf "%s\n%f" fasta.Name fasta.GC_Content)
        static member CalculateGCContent (fasta:Fasta) = 
            let emptyContent = { C_or_G = 0.0; Other = 0.0; }
        
            let calculate content = 
                (content.C_or_G / (content.C_or_G + content.Other)) * 100.0

            let addContentToFasta fasta (content:double) = 
                { fasta with GC_Content = content; }
                
            fasta.DNA
            |> Seq.fold (fun acc item ->
                match item with
                | 'C' | 'G' -> { acc with Content.C_or_G = acc.C_or_G + 1.0; }
                | _ -> { acc with Content.Other = acc.Other + 1.0; })
                emptyContent
            |> calculate 
            |> addContentToFasta fasta
    
    let strToFastaSeq (str:string) = 

        let split (splitter:char []) (str:string) = str.Split(splitter)
        let splitOnNewLine (str:string) = split [|'\n'|] str
        let splitOnChevron (str:string) = split [|'>'|] str
        let hasContent (str:string) = if str = System.String.Empty then false else true
            
        let emptyFasta = { Name = System.String.Empty; 
                           DNA = System.String.Empty; 
                           GC_Content = 0.0; }
        
        let entryToFasta (lines:string []) =
            lines
            |> Seq.fold (fun fasta line -> 
                match fasta.Name with
                | "" -> { fasta with Name = line; }
                | _ -> { fasta with DNA = fasta.DNA + line.Trim(); })
                emptyFasta
        
        str
        |> splitOnChevron
        |> Seq.filter hasContent
        |> Seq.map splitOnNewLine
        |> Seq.map entryToFasta

">Rosalind_8327
GTTGAAATTACAATTGTCTCGACGTTCTAAATTAGATTACTTCAGTGTACTGCGCCTATT
CGTACACCGGACGACCGTGACGAATTCGCTGCTTTCCAGAAAACGTCCTAACATCCATAC
CCGGACTCGCGGACCTGAATTTTTCCATGCGCGTACCTGGTTAGGTCAGAGAACGTCAGT
TGGCAGCTCATAGGTGACTTACCCCGTACCTCATTTCGGTTAGGGGCGCTCGAGCCCCTG
GAATACGAACAGTTTCAGCGCACAATCACTCGTTGAGTTGCCTGTAAGAAGAAGGAGGTA
CACTACAAGCCCCCCCAGGCGGTCCCTCACAGGGTGTTTGGTTGCGGATCATTAACCCGT
AGTGGATCCGACAGCTCGCGATTAGCGTGGACGAGATTGCAGTTCGCCATTCAATTGACG
GACGTGACCGTGTAGTGCTCTGTAAGTACCTCAGGTGAGTCCCCTGAAGAGGGCCCACTT
ACTAGGCTGAACACCCCGAGCGCCGCAATTGTTTTACTCAACACCTAGAAACAGCCTGTA
TAAGAGGAGAGTATGCAGCCAACGACCTAAAGTCGAAACCGCCGGATTTAAACATGTCTT
TTCAGTACCTGTTCCCAAAAGTAGTTGCCCATGTCCCGTCTCCCATGTTAAAAGGTATAT
GTAGAGAAGCTTGGAACCGATCACCCTCGGGAGCAGTAGAAAAGCTATTGGGGCGGCCCT
CAAAACCCGGATTGCAATCCCCGAGGATGTAACGAGTCTATCCGACGGTGCCCCCTCACC
CGAGGAATCAGAGCGGTCAACCTTGCGACGCTTGTAGACAAAGTTGCGAGAAGCGCAGGT
AGGTACGGGGAAGGACTCGAATACTGAAAACGCGTCGAGAGCCCTCCGCGTTCTATTAGT
TCCTAAACCGGATCTACGTATTAGGAGG
>Rosalind_4695
GCGAAGGGTTGCAACCATTGTGCTACTACGGTGGCCGAAGCGAATCCATGCCAGTGGAGG
AGTATGATGCGTTTTATATCCATCACCCAGCTTGTCCTCTGCTTTTAGTCGAGAGGGTTA
TCGTGTCAGAAAGCATTAGCGCGTATGGCCATTTTCTTATGTGGTGCCGGCCTAGAATGC
TCCTTGCGTCTTTTACAATCGCAAGTAGCGAGTGAGCCCGCGGGCACCTTGTCCGGTGAC
GTCCTGCCGACTCATAAGCATGGCGGGGGTGTCGTTCCAGTACACTTGCTTGGTAAGAAT
TGATTGGCGTCTGGATTCTAGGTTCAAAATGTAAACCCGATGCTCCCCCTTGATGCGGTC
ACTCTCGCCGTGACCTGGAAACTAGCTGTGGCTCGCAATAGAGAGGACGCAAGCCCCCGC
AACTCACATGGTTTGTGCTGTTGAGATAGGAAACACTTCTCACTCACTTTACTTTCTGAG
ACTTTTTCGTATATCCTATACTGTGGTCCGAACTCCTAATGAGTCTAAGTCGTGGTTGCG
CGCGATTGCACTGTTTGAAGGCGTATGTGATGTTGGAACCGTTATGATCACGGTTTCAAG
CAAGAGATGAGCTAACTTGTAGCAGGCCGAACTCATATGCGCATCTACGTCCCCCGCAAA
TAGTCACCCTAGGTCCCGACGTTTCATGTTTAATTAGCGGGCCCATGCGGTACGTACCTG
TCCTTGTCGCATGGTCCTACGACTTGGCATCACCAGTCGAGCTGCTGTCGCAAATCTACA
ACCAAGCCAACCGAGGTTTAGAGTGCAATACTTGTCGCAGGGGTACGATTAAGTATTTGT
GGCAGGTTAACGAGGAACGCTCTATGATATTACCTAAGAAACATTCCCGGCTCTAAGTGC
GATTGAATAGCGTCAACCGGTGGCTAAATACTGCGGATTGATTAGATGATAGTGCAGCCT
GAGCGCCTGCGCCAGAG
>Rosalind_3711
GCTACTGGACAACACAAATTCGAATATGCTCATCTTGCAGAGAGACGCTCGAATCTCATC
TATCATGTAAGGATCCCAGCACCCGGCCGAGCCTGGGGGACGAGCCTGTATACAGTTCCT
CGGATTCCGACGACAGGGATAGCTTACGGAAATCAACGTGTCAGACCCTTGCTGTCGGCC
GTGAGTGGCAAAGACGCGAACCCGGATCGGGCTCCGGGACTGTACGTTACCCGTTCCGCA
GAAGGGGTTTCTGGCGGTTTCTTTCGGCGCCATAAATCGCGCTGTCCTAGCCACGACTGC
GGACTGTTAAGACCTCCAATTGATGAATGCAATGTCTTTGTTGTGCACCACACGAACGGG
CAGCTTTTAACCTCAATAGTATCTGAGGCTTCCTACACGTGAATGGCTTACCGTGGATTC
TGGGGTAATGGGAATCTATCGGGCGAGGCGGGCAGCAGAGTCATATGTGGCGAGACCCGG
TAGGGGCCTGCGACTATCGCGTGTGACATCATAATAGTAGGTTTTGCTGTGGCCAATAAT
AATACTTGCGCAACATCTTCACTGAGTGGTTGTAGTTTTTGGTAGCAGTGACATCTTAAA
ACTAAGCTGTAACTAATGGTCTTGTTTCTAAGTCTCCCTCCTGGCTAAAAGCGAGACAAA
AGGTCCCGTAATGATGTGGCTCGTATGGTTACTAGTGCCTCGTAGGCTGTTCTTAGAGGC
ATCACCATGATGTCCGTGATAGACGTAAATGGGCATCTTCGGGACGTTCCTGGGTTCTGA
AAGCGACGGGAACAAATTAATATCGACGGCTAGCTACTGCGACTCCTTAAAACTGGGCAG
GTGGGATCCGGGTAGACGCTTGGTTACTGTTAGCATTAAGCTCTGTCTCGCCCGGTTTCT
TATTTTGATCACCGCGACACTGCTCGTTGTTGGACATGGGTGGTAATTTTGGTTATCTCA
GCGTGGTGCCAGCATTCAATAGCGC
>Rosalind_6622
TAGTGTTATCTATAGCGCCTTCGTAGAGGCTCAACTCCAGATCGTAAGACTAGTGCCCGC
CGGTATTCGTAAGGTAGCGACCTATGTCGAACCCCTACGAAGAAAGCCCACCAACTAAAT
TAATGTCTGTTCTTAAAGTGGAGCCGCGAGCCAAGTGGGCCCACTCCCCTATCCCTGGAA
GGCGCAGGCCATGCATTAGTGTTTCATTGAGAAATAGTTGGCACTTAACAGACAGTATTC
CACCTAAGGGTAAGTGTCATCAGTGTACAGGGGCGCGTCAATACTAGCGTTAAAAGTAGT
AGTGCCGAGTCTCTTAACTAGCGCGCGATCTCGATGTTGCAATATAGCGGTACCACGAAA
GCAAGACCATCCGGCTCCTTAATCGTACGACAGCTCACCTCCCCGTTGTGTACTGGTCAG
GCGCATCCACACCGTTCCCCGCGAGCCGAGTACAAAAGGGGGCCAGGCCGCCTTGGGTGG
AGATTCCGATAGAGTAGCTGGCGGGATTTTTTATACGGCGTGCATAAAGCTGACTGGTGT
AGGCCTTGTTGGAAGTGAGCCGACTTGGGTGATCCTGTTCCGGCCTCTAGGTCACTTAGT
TTGTCAAGGCTCATCAGTTCTGACTAAGATCTATTTTAATAATGCATTTTCCGGACATTT
CGGCTAGGAGTTTTGGGTCCGTCGCAAACTTGGCGTACCTCTTGGCGCTAGCTAAGTGGA
TGATAATACTGCGCCGCCGCCGAGGCACAAATTAGTGTCAAGCTCGATAAGCAATTACGA
AAATGTCTGCGGGCAGCTAAAATGCTGGGATCCTGGATATTCAAGACGGAAAAGGCTAAA
TCGATTCGTGGGTCTTGGAACCCGTCCGCGTTATTGTAAAAGTCGAG
>Rosalind_8256
ATTACCGGCCCCTTGTAAATCGAGCGGTCAAATTTTCGGGTCCGGACCACTATCGTCCAC
ACTAGGGGGCGGGATCTCGGGTGTTTTGTATACGGACTCATAACCTTCATCGCTATATGA
CTTGCTACTAATAGGATCCGGATTATAAATGACGCACTTCGCCCCGAGGCGGCGGCGTTC
AACTGCATATAGCCGATGATGAACGCAGCTAACAAACTGCGCATATACTAGGAAATGACA
GCGGTGCTAAGTAAAGGGCCACAAAGCTGCCGAACTTTGAGGCGTATCCGCCCCCTTCCT
TTTCGCGGCCGGCCTCTAGATGAAACCTCGTCCACAGCTGAAACGTATACCACCGCTCCA
GGATAATGGTTTGAAGAAACACCCGGGGCAACGAGCGCCGAATGATCTCCCCCGTACCAA
AGGTTGTTCACATAGCTTCCCGCCATTCACCGTGAGTAATGAACTCTGGCTTTTTATCCC
TATGAAAAAGTATGCGTCGTTGATTTTTGGTGGACTGTCGATATACTTAGGTCCTTAAGT
CTAAGTCATCCTTTACAAACTCTGCAGTAACGCTAGTGCATACGCCTTTCTGACCGATGC
AGTGGCCCAATTATAGTCAACGCATGACTCATTTACGCGCTATCCCAGATCGCCGTCGTC
GTGGGACCCCGTACAGGTTCGAGACCAACAAGCCGTTTTTGCGCGGGATTACGATGGCGT
TAATGGCGGCACGACGGTGGGTTGGTTGCAACCAACATAAGGCTTTTGGGGCTTGATCGC
CGCAGCGCCCTGACAAGGGCATCGCACGTACGATTGCAAGATACGCGAGGAGGTAAAACG
TTCGTGACCGATAGTACTCTTTGACTTATCTCTTTACTT
>Rosalind_1098
GGCAGAGCGACGTACGTTATTATCGGCTGTCTCATGCAAAGGGTGGCGTCAGGGGCAAGA
AAGCACCATTTGCGATACCTATGCCTCTATAGTACTTTCACTGCCTGGCAAAACCAAGGA
CCCCCCCAGAGCTTGTCGCCGATCCTTGAGAGCCGCTCGACACGCTTCTTATGGCAGAGG
CAGCGCGTCTAATGGTAAACGTCAACAGATTCTATCCGGGGGTTAGACCATGATCTAGTT
GTGCAATTTGATGATCCAATTAGAAGTCTTGACAAGAGAATTGAGCTCGCGACCCACGAG
CTCCATGACGATATGTATATGGAGGTTGTTAGCTGGGGGGTTCCAAAGGTTCAGCACTAC
CACCCACACTCCTATGGGCCCCGATCGACGTCCTATCGGCGGTAACCAAAGGACGAATGT
TCTAGCAGATCGATTTGCTCATCGTAGTCAATGGGGTGGCGGTGTCAAAACTCGAACGGC
TACGGCTGAGTGTCGTCTCTTTGAGAATAAGAGCCAGGCCCTTAGTGGATGGTGTGCATC
GTATATCGAGGGCTCTTGCCTGAGCGTATTGCATTGACACTCGGAGCCGGACAGTTGTGC
GACACGTAATATAGTTCTACGAAGTGCTGTTACGTTCCGCTCGTGCTGGGATATCGCCGA
GCGTGACGGTACATAATCGCAGGGTTTCGACGTGATCAGCCCTGTTAGAGTCCATAGCTT
AGGAAAGTCATATCCCGATAATATGACACTCCTCAGATTGACTTCAAGACGTCGGATAAC
GGGCACATCGTAAGGACGACCGACTCCGTGTTGCTACTGGGTGCGCGCTAAGGTCCACAT
ATGTCCACTAGTTTCCACTGATCCGCTAATAATCTCGCGTCTTAAAGGCTCCCGAATGAC
AAACAGTGGGGTCACGGCGTAACTTATTGAAAAGTAGAT
>Rosalind_0841
TTGAGCCGCGCGACGGCGCATACCTATCCTAAATAGCTCATTGAGAGCAAAGCCTCAGAC
CTACGTTATTGAACAATGAGATCGAACTTAGTATCACGGCAACATTGATCGAGCTAATTG
CGTTTAGTTCTGACCCAATGTCGGGAGGTTTAACTCTATGAGCGCAAAACGCTACCGAGT
CTCACCTTTTGAAGCTATAGCTTCATTACTTTCGAACTCGTTATTCCACATCTAGCCAAT
TAGATCTAGTCTGGGAGACTTGCGGGAGCCCGACCTCAACTCCTTAATCGCAGATTATAC
CGCGCCGTTTTTGTCTGGGTGGATAATGTATAACCGTATGCATTTACGCACAGCGTCCCT
GTTAGCCGATCGGAAGATAGGCGGTGGTGAATTGTATGCTTCGCAATAAGCGCCGATTCC
CCGACTAACAGCGTGGCTAAAGTAGAGGTGCGTCTATATGGTCCGCCAAAAAAGCGAACA
AAATAGTATAATCACCTATACCTTTGCAGTGGGCGTTGGGTGGTGTTCTCACCTGCAATC
AAAGAGCCCACAAACCCTAGCGAGTGCCGAAACACAGCAATTGTCATGTGCCTGGTAACG
CGCAGCTCGCGGTCCCAAAGGCCTAAACTTCGTGGCCGAATTTAGGAACTCCTTGCCGTA
TAGCCACGCGCAACTAATTCTTGCGAACGCCGTAACAAGTTAGTATGTTTGGCGCAATCA
CGTCGCGATCGTCAATTGTCATGAGATAGGGCGCTGCTCGGGGTGATCCGAAAAGAAGCA
GGTCCTGGCAACAGGGTAGACACATCGGTAATTGCAGGAGCACTGATAACATGCAAGGTC
GATCATTGAAGGTAAATTTTAGTACCATAGACGCTCATCGTATTCAGTAATTCTTCCACT
CCAAAATCTGA"
|> Fasta.strToFastaSeq
|> Seq.map Fasta.Fasta.CalculateGCContent
|> Seq.maxBy (fun fasta -> fasta.GC_Content)
|> Fasta.Fasta.print